# Numpy 

Quelques exemples de commandes dans Numpy pour voir les bases de la création de matrices, vecteurs, scalaires ainsi que les opérations possibles dessus.
Cela permet également de se rendre compte que Numpy est très optimisé pour les calculs en vue de sa vitesse par rapport à Python classique.

In [1]:
import numpy as np

In [2]:
# Creation de tableau
np.array([1,2,3])
# Dans un tableau Numpy tout les élements sont du même type
np.array([3.14,7,23.2])

array([ 3.14,  7.  , 23.2 ])

In [3]:
# On peut forcer le typage
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)
# Sans le dtype=int le tableau serait en float

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Matrice de 3 x 3 avec des nombre random entre 0 et 1
np.random.random((3, 3))

array([[0.79437493, 0.50957911, 0.43557349],
       [0.3451661 , 0.66350029, 0.69424691],
       [0.37156429, 0.19287225, 0.03514653]])

In [10]:
# La matrice identité de taille 3x3 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Propriétés tableaux

x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


In [12]:
print(x1)

# Pour accéder au premier élément
print("premier élement",x1[0])

# Pour accéder au dernier élément
print("dernier élément",x1[-1])

# Tableau de dimension 2
x2 = np.random.randint(10, size=(3, 4))
print(x2)

print("ligne 1 colonne 2 :", x2[0,1])

# On peut aussi modifier les valeur
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

[3 6 2 3 8 9]
premier élement 3
dernier élément 9
[[2 8 8 8]
 [2 2 8 8]
 [5 8 5 1]]
ligne 1 colonne 2 : 8
[   3 1000    2    3    8    9]
[3 3 2 3 8 9]


In [13]:
x1

array([3, 3, 2, 3, 8, 9])

In [14]:
# Concaténation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [15]:
# Merge 2 tableaux
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
# Calcule sur tout le tableau en numpy

tableau_large = np.random.randint(1, 100, size=100000)
(1.0 / tableau_large)
%timeit (1.0 / tableau_large)
# L'opération prend presque 1000 fois moins de temps.

132 µs ± 2.77 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
%timeit calcul_inverse(tableau_large)

187 ms ± 8.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arrondie

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [19]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [20]:
x = np.random.rand(3,3)
x > 0.5

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False, False]])

In [21]:
np.where(x > 0.5)

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0], dtype=int64))

In [22]:
L = np.random.random(100)
np.sum(L)

52.55438144371627

In [23]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

8.37 ms ± 439 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
47.9 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
